#!/bin/bash

function List(){
    clear
    purplecolor "+---------------------------------------------------------------------------------------+"
    redcolor "| Number  images_command    Website                      Local_Path           "
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 1       epel6         $TUNA        $EPEL6   "
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 2       epel7         $TUNA        $EPEL7"
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 3       centos7       $TUNA        $CentOS7"
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 4       centos6       $TUNA        $CentOS6"
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 5       mariadb   $TUNA        $Mariadb"
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 6       remi           $TUNA       $REMI"
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 7       mongodb     $TUNA        $MONGODB"
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 8       zabbix6       $TUNA        $ZABBIX6"
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 9      zabbix7       $TUNA         $ZABBIX7"
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 10       influxdata6         $TUNA        $influxdata6 "
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 11       influxdata7         $TUNA        $influxdata7 "
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 12        rock               $TUNA        $ROCK"
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 13        docker              $TUNA        $DOCKER" 
    purplecolor "+---------------------------------------------------------------------------------------+"
    redcolor "|                 Curl "
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 14      glibc        $REDSLEVE         $GLIBC"
    purplecolor "+---------------------------------------------------------------------------------------+"
    greencolor "| 15       nginx         $USTC        $Nginx "
    purplecolor "+---------------------------------------------------------------------------------------+"
}

function RUN(){
    clear
    skybluecolor "+------------------------------------------------------------------------+"
    skybluecolor "|                   Rsync Script          "
    skybluecolor "+------------------------------------------------------------------------+"
    skybluecolor "| This script is only allowed to execute on the CentOS system"
    skybluecolor "+------------------------------------------------------------------------+"
    skybluecolor "|         Rsync base packages mirrors     "
    skybluecolor "+------------------------------------------------------------------------+"
    skybluecolor "|           For more information please visit docs                 "
    skybluecolor "+------------------------------------------------------------------------+"
    skybluecolor "| If you are running for the first time, check your environment with the check option."
    skybluecolor "| You can use the list to see which images can be synchronized."
    skybluecolor "+------------------------------------------------------------------------+"
    skybluecolor "|Use the corresponding image name to sync, or use all to sync all"
    skybluecolor "+------------------------------------------------------------------------+"
}
