#!/bin/bash
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/centos6.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/centos7.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/gilbc-2.15-wget-list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/mysql.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/zabbix-for-centos6.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/glibc2.17_for_6-wget-list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/nginx6-wget-list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/zabbix-for-centos7.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/docker.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/glpi.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/nginx7-wget-list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/epel6.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/mariadb.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/pinpoint-wget-list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/epel7.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/mongodb3.6.list && cd -
cd config && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/config/remi.list && cd -
cd incloud && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/include/stack.sh && cd -
cd incloud && curl -LO https://raw.githubusercontent.com/slmoby/script/master/mirror_project/include/stack.sh && cd -
